sudo: required

services:
  - docker

env:
  global:
    # DOCKER_USER
    - secure: HjpHE/FOHCTAA8EuyPnJ8seZsNPWWTND+kApJ0rc88vq6rS/U0RkgHXJQf3D8q1/IKc9cZUzRzdc0EszAs8siaodNegCedpm8vaREwFAGFHJkD1csuC4aqGUB4S185U2wKLFOyTJ0iMx53ZQKrLNkUXDZAZZEP5K8sMa1V9zyJ0cU3kzo6COW3BBeDKYNYjQv+yiEqCKmEkY1617F9fgZs2F5e5SHfrHplgX+JJbjTKiyBxzWVZOfBPf2QQ6Cd/jM0lpSU9PhKl61pU2ioUqZ3Ij5GYZIShjd9Zyy/h5s0xmHPj7cfnxbyGuWa2taXnUfbziZR/Lvtj7iPxFwQzv+T7No7Urw8y2FGf25+6SPc778DsIj7m3hmDLChX51dgqIqWDun4RU/KAKhoZXBRckbvDpe1OqOR2GRcO2CJxIiTP/3Uow0Zf7RPAU2KLnYNtdSdi/ym08sJZ8C5UcXe7w097iMJ4fPo+YdxHepz6hnTGiC7NmuPJDAxdgE4vrLACTEc4hso3D/THOpPk1J3zjJJh2D0g7cv4UYhxEvTKIb8ORrM8srSatMzE8TVAXrm5GLVQWdFdIyXODjy0tRMldCCB7pmmAoi8/GPAw2cXRtNKLZw+PFth2FDNs3wowSiEhzNjJBWa5q7rgZmvSfANHK94dd18IVKiVG/U7VYy6VQ=
    # DOCKER_PASSOWRD
    - secure: AH7kIsjO/ClKbuYVfitj8zTexc91FAuX5B59o858/qvGaruiV47lohNVZnGmQmFOMJvF5ef1sVqhnpVMnQkjFacmMduXQRC0vsJDXF6F5xNC1JhZ83CXKL4jkOxsvSueEjJr+i1ZBlBhhBg23viaa/FyFPu0Phzh28VyAQ8fM/e7Fb+Wew2Hd8zxUZ37g5SFJ+Tfg0v5dGFwcqydESNjcFIi6EvrFdm9gUVRlLhIundrtD0CHakFycel+01NKwoPCDKLf4FfcbJkbZz38saThfc6ZY32d8d0HQIb3RmGBrS9BXMFiHQ2DhIZUj9O7FBgp5SO7coZYQqpo8imIFI/N1ph714L8zhoYnI+LG9+T4N+m26rjR/LUMXqsYQHRMv1G88rbwUKLNSaY6qbrHg9OGR9Q2REPO79nUI0qdAZgrEuXGiU17a2sAy4B1xQ5c5hrhNTHS+5GG5E4BS9/R7ELJ4K3VRwW2YFO5oW8XWSeJw9yQdNkT92q6t/WN13lMrjNTcHO5/2ibHlwJkdyixFqCGck6gQaCQjXR3lC4LPQus8vN7LLPrh1cDtpaxEuQAGTlVsFpgBTmJ/DOtJBnTt9D0a4suPPAmoBVEy5Sj2BEHFj3egRY1mrQ24piubM2LG7U3kzqHI4owLffTCveUtdrWA2yj9f2M2Uw5chdyRQL4=

  matrix:
    - ALPINE_VERSION=3.6 OCAML_MAJOR=4.04 OCAML_VERSION=4.04.2
    - ALPINE_VERSION=3.6 OCAML_MAJOR=4.04 OCAML_VERSION=4.04.1
    
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker build --build-arg=$ALPINE_VERSION --build-arg OCAML_MAJOR=$OCAML_MAJOR --build-arg OCAML_VERSION=$OCAML_VERSION -t efcasado/ocaml:$OCAML_VERSION .
  - docker push efcasado/ocaml:$OCAML_VERSION
